routes:
  front_controller_index:
    method: 'GET'
    path: '/'
    class: App\BlogBundle\Controller\FrontController
    action: index
    name: home_page

  front_controller_edit:
    method: 'GET'
    path: '/edit'
    class: App\BlogBundle\Controller\FrontController
    action: edit
    name: edit_page

  post_controller_list:
    method: 'GET'
    path: '/intranet/post/list'
    class: App\BlogBundle\Controller\PostControllerAdmin
    action: list
    name: list_post

  post_controller_create:
    method: 'GET, POST'
    path: '/intranet/post/create'
    class: App\BlogBundle\Controller\PostControllerAdmin
    action: create
    name: create_post

  post_controller_edit:
    method: 'GET, POST'
    path: '/intranet/post/[i:id]/edit'
    class: App\BlogBundle\Controller\PostControllerAdmin
    action: edit
    name: edit_post

  post_controller_delete:
    method: 'GET'
    path: '/intranet/post/[i:id]/delete'
    class: App\BlogBundle\Controller\PostControllerAdmin
    action: delete
    name: delete_post
