routes:

  security_controller_register:
    method: 'GET|POST'
    path: '/register'
    class: App\BlogBundle\Controller\SecurityController
    action: register
    name: register_page

  security_controller_login:
    method: 'GET|POST'
    path: '/login'
    class: App\BlogBundle\Controller\SecurityController
    action: login
    name: login_page

  security_controller_login_check:
    method: 'GET|POST'
    path: '/login_check'
    class: App\BlogBundle\Controller\SecurityController
    action: loginCheck
    name: login_check_page

  security_controller_logout:
    method: 'GET|POST'
    path: '/logout'
    class: App\BlogBundle\Controller\SecurityController
    action: logout
    name: logout_page

  front_controller_index:
    method: 'GET'
    path: '/'
    class: App\BlogBundle\Controller\FrontController
    action: index
    name: home_page

  front_controller_contact:
    method: 'GET|POST'
    path: '/contact'
    class: App\BlogBundle\Controller\FrontController
    action: contact
    name: contact_page

  front_controller_edit:
    method: 'GET'
    path: '/edit'
    class: App\BlogBundle\Controller\FrontController
    action: edit
    name: edit_page

  front_controller_post_list:
    method: 'GET'
    path: '/post/list'
    class: App\BlogBundle\Controller\FrontController
    action: listPost
    name: list_front_post

  front_controller_post_show:
    method: 'GET'
    path: '/post/[i:id]/show'
    class: App\BlogBundle\Controller\FrontController
    action: showPost
    name: show_front_post

  front_controller_comment_create:
    method: 'POST'
    path: '/post/[i:id]/comment'
    class: App\BlogBundle\Controller\FrontController
    action: createComment
    name: create_front_comment

  post_controller_list:
    method: 'GET'
    path: '/intranet/post/list'
    class: App\BlogBundle\Controller\PostControllerAdmin
    action: list
    name: list_post

  post_controller_create:
    method: 'GET, POST'
    path: '/intranet/post/create'
    class: App\BlogBundle\Controller\PostControllerAdmin
    action: create
    name: create_post

  post_controller_edit:
    method: 'GET, POST'
    path: '/intranet/post/[i:id]/edit'
    class: App\BlogBundle\Controller\PostControllerAdmin
    action: edit
    name: edit_post

  post_controller_delete:
    method: 'GET'
    path: '/intranet/post/[i:id]/delete'
    class: App\BlogBundle\Controller\PostControllerAdmin
    action: delete
    name: delete_post

  comment_controller_list:
    method: 'GET'
    path: '/intranet/comment/list'
    class: App\BlogBundle\Controller\CommentControllerAdmin
    action: list
    name: list_comment

  comment_controller_create:
    method: 'GET, POST'
    path: '/intranet/comment/create'
    class: App\BlogBundle\Controller\CommentControllerAdmin
    action: create
    name: create_comment

  comment_controller_edit:
    method: 'GET, POST'
    path: '/intranet/comment/[i:id]/edit'
    class: App\BlogBundle\Controller\CommentControllerAdmin
    action: edit
    name: edit_comment

  comment_controller_delete:
    method: 'GET'
    path: '/intranet/comment/[i:id]/delete'
    class: App\BlogBundle\Controller\CommentControllerAdmin
    action: delete
    name: delete_comment